################################### Training options ###################################



#--- Data Parameters ------------------------------------------------------------------#
train_path : "/home/yannic/master-thesis/data_air/prsa_data.parquet"
val_path : "/home/yannic/master-thesis/data_air/prsa_data.parquet"

src_sequence_size : 11
trg_sequence_size : 11
src_pad_idx : 0
trg_pad_idx : 0

nsamples : 0.01


#--- Training parameters --------------------------------------------------------------#
epoch : 10
batch_size : 64
window_size: 256
loss_func: "rmse" #Options: r2, mse, rmse
learning_rate: 0.001


#--- Model Parameters -----------------------------------------------------------------#
d_model : 512 # The Model dimensionality
d_inner_hidden : 2048 # Dimensionality of the hidden layer in the Positionwise Feed Forward Module
d_key : 512 # dimensionality of the key vector
d_value: 512 # dimensionality of the value vector
d_sequence: 512  #dimensionality of the sequence vector after the 'Embedding' (fcn)

n_head : 8 # Number of attention heads
n_layers : 6 # the number of layers in the encoder / decoder -> 6 is the standard
lr_mul : 2.0 # The learning rate multioplicator for the scheduled learning rate
seed : No

dropout : 0.1
embs_share_weight : False
proj_share_weight : False
scale_emb_or_prj : 'prj'


#--- Logging Parameters ----------------------------------------------------------------#
output_dir : "./output"
use_wandb: True
save_mode : 'best'


#--- Others ---------------------------------------------------------------------------#
cuda : True
label_smoothing : True